name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo:latest
          docker stop flask-ci-cd-demo || true
          docker rm flask-ci-cd-demo || true
          docker run -d -p 5000:5000 --name flask-ci-cd-demo ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo:latest
